name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Publish package
        run: |
          echo "const fetch = require('node-fetch'); global.fetch = fetch;" > fetch-polyfill.js
          node fetch-polyfill.js
          npx jsr publish
